# Generated by Django 3.1.1 on 2020-09-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpttapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='body',
            field=models.TextField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='mydata',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
